<h1> Name: Eshan Mehrotra

In [46]:
import pandas as pd
import math

## Read Scraped Data and Clean

In [47]:
rawdf = pd.read_csv('3.csv')
rawdf.head()

,Name,Price,Link,Market Cap,Circulating Supply,Total Supply,Max Supply,All Time High Value,All Time High Date,All Time Low Value,All Time Low Date
0,OKB,$21.89,/currencies/okb/,"$1,309,901,623.94","60,000,000 OKB","300,000,000 OKB",No Data,No Data,"Jan 01, 2000",No Data,"Jan 01, 2000"
1,Basic Attention Token,$0.88,/currencies/basic-attention-token/,"$1,315,319,646.17","1,495,079,069 BAT","1,500,000,000 BAT","1,500,000,000 BAT",$1.92,"Nov 28, 2021",$0.06621,"Jul 16, 2017"
2,Chiliz,$0.22,/currencies/chiliz/,"$1,324,652,399.71","5,975,068,035 CHZ","8,888,888,888 CHZ","8,888,888,888 CHZ",$0.8915,"Mar 13, 2021",$0.004001,"Sep 27, 2019"
3,Loopring,$1.01,/currencies/loopring/,"$1,340,276,154.58","1,329,247,433 LRC","1,373,873,440 LRC","1,374,513,896 LRC",$3.83,"Nov 10, 2021",$0.01986,"Dec 18, 2019"
4,Curve DAO Token,$3.17,/currencies/curve-dao-token/,"$1,404,854,708.12","443,206,806 CRV","1,687,553,339 CRV","3,303,030,299 CRV",$60.50,"Aug 14, 2020",$0.3316,"Oct 25, 2020"

In [48]:
rawdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 100 non-null    object
 1   Price                100 non-null    object
 2   Link                 100 non-null    object
 3   Market Cap           100 non-null    object
 4   Circulating Supply   100 non-null    object
 5   Total Supply         100 non-null    object
 6   Max Supply           100 non-null    object
 7   All Time High Value  100 non-null    object
 8   All Time High Date   100 non-null    object
 9   All Time Low Value   100 non-null    object
 10  All Time Low Date    100 non-null    object
dtypes: object(11)
memory usage: 8.7+ KB

In [49]:
rawdf.describe()

,Name,Price,Link,Market Cap,Circulating Supply,Total Supply,Max Supply,All Time High Value,All Time High Date,All Time Low Value,All Time Low Date
count,100,100,100,100,100,100,100,100,100,100,100
unique,100,89,100,100,100,100,59,100,71,97,77
top,OKB,$1.00,/currencies/okb/,"$1,309,901,623.94","60,000,000 OKB","300,000,000 OKB",No Data,No Data,"Nov 16, 2021",No Data,"Mar 13, 2020"
freq,1,7,1,1,1,1,42,1,7,4,19

In [50]:
rawdf.columns

Index(['Name', 'Price', 'Link', 'Market Cap', 'Circulating Supply',
       'Total Supply', 'Max Supply', 'All Time High Value',
       'All Time High Date', 'All Time Low Value', 'All Time Low Date'],
      dtype='object')

## No Data check for Raw File

In [51]:
[(col,"No Data" in rawdf[col].values) for col in rawdf.columns]

[('Name', False),
 ('Price', False),
 ('Link', False),
 ('Market Cap', False),
 ('Circulating Supply', False),
 ('Total Supply', True),
 ('Max Supply', True),
 ('All Time High Value', True),
 ('All Time High Date', False),
 ('All Time Low Value', True),
 ('All Time Low Date', False)]

## Removing $, symbols and Crypto Abbreviations to pick only values

In [52]:
rawdf["Price"] = rawdf["Price"].str.replace("[$,]","",regex=True)
rawdf["Market Cap"] = rawdf["Market Cap"].str.replace("[$,]","",regex=True)
rawdf["Circulating Supply"]=rawdf["Circulating Supply"].str.replace(",","",regex=True).str.split().str[0]

In [53]:
# rawdf["Total Supply"]=rawdf["Total Supply"].str.replace("No Data","",regex=False).str.replace(",","").str.split().str[0]
# rawdf["Max Supply"]=rawdf["Max Supply"].str.replace("No Data","",regex=False).str.replace(",","").str.split().str[0]
# rawdf["All Time High Value"] = rawdf["All Time High Value"].str.replace("No Data","",regex=False).str.replace("[$,]","")
# rawdf["All Time Low Value"] = rawdf["All Time Low Value"].str.replace("No Data","",regex=False).str.replace("[$,]","")

# Indexing done to pick up the value and not the Crypto Abbreviations. Always 1st elementwhen split by " "
rawdf["Total Supply"]=rawdf["Total Supply"].str.replace(",","").str.split().str[0]
rawdf["Max Supply"]=rawdf["Max Supply"].str.replace(",","").str.split().str[0]
rawdf["All Time High Value"] = rawdf["All Time High Value"].str.replace("[$,]","",regex=True)
rawdf["All Time Low Value"] = rawdf["All Time Low Value"].str.replace("[$,]","",regex=True)

# Replaces all No Data or No values with None in the entire df
rawdf.replace({'No Data':None,'No':None},value=None,method=None,inplace=True)

In [54]:
rawdf.head()

,Name,Price,Link,Market Cap,Circulating Supply,Total Supply,Max Supply,All Time High Value,All Time High Date,All Time Low Value,All Time Low Date
0,OKB,21.89,/currencies/okb/,1309901623.94,60000000,300000000,None,None,"Jan 01, 2000",None,"Jan 01, 2000"
1,Basic Attention Token,0.88,/currencies/basic-attention-token/,1315319646.17,1495079069,1500000000,1500000000,1.92,"Nov 28, 2021",0.06621,"Jul 16, 2017"
2,Chiliz,0.22,/currencies/chiliz/,1324652399.71,5975068035,8888888888,8888888888,0.8915,"Mar 13, 2021",0.004001,"Sep 27, 2019"
3,Loopring,1.01,/currencies/loopring/,1340276154.58,1329247433,1373873440,1374513896,3.83,"Nov 10, 2021",0.01986,"Dec 18, 2019"
4,Curve DAO Token,3.17,/currencies/curve-dao-token/,1404854708.12,443206806,1687553339,3303030299,60.50,"Aug 14, 2020",0.3316,"Oct 25, 2020"

In [55]:
# Rechecking if any still has No Data values
[(col,"No Data" in rawdf[col].values) for col in rawdf.columns]

[('Name', False),
 ('Price', False),
 ('Link', False),
 ('Market Cap', False),
 ('Circulating Supply', False),
 ('Total Supply', False),
 ('Max Supply', False),
 ('All Time High Value', False),
 ('All Time High Date', False),
 ('All Time Low Value', False),
 ('All Time Low Date', False)]

In [56]:
rawdf[rawdf.isin([""]).any(axis=1)]

Empty DataFrame
Columns: [Name, Price, Link, Market Cap, Circulating Supply, Total Supply, Max Supply, All Time High Value, All Time High Date, All Time Low Value, All Time Low Date]
Index: []

In [57]:
rawdf[rawdf.isin([None]).any(axis=1)]

,Name,Price,Link,Market Cap,Circulating Supply,Total Supply,Max Supply,All Time High Value,All Time High Date,All Time Low Value,All Time Low Date
0,OKB,21.89,/currencies/okb/,1309901623.94,60000000,300000000,None,None,"Jan 01, 2000",None,"Jan 01, 2000"
6,TrueUSD,1.00,/currencies/trueusd/,1477517905.32,1477731617,1477731617,None,1.36,"May 16, 2018",0.9179,"Mar 13, 2020"
8,Kusama,178.21,/currencies/kusama/,1504452239.18,8470098,9651217,None,623.75,"May 18, 2021",0.9158,"Jan 14, 2020"
17,Audius,1.19,/currencies/audius/,727730964.92,608321992,1078933974,None,4.99,"Mar 27, 2021",0.07774,"Nov 03, 2020"
19,XDC Network,0.06,/currencies/xinfin/,775661476.12,12305012699,37705012699,None,0.1939,"Aug 21, 2021",0.0001571,"Jun 20, 2019"
21,1inch Network,1.77,/currencies/1inch/,829627731.05,468181744,1500000000,None,7.87,"May 08, 2021",0.7612,"Dec 29, 2020"
24,Pax Dollar,1.00,/currencies/paxos-standard/,942881832.35,945642940,945642940,None,2.02,"Nov 16, 2021",0.8728,"Mar 13, 2020"
25,Holo,0.01,/currencies/holo/,943400211.23,173174228547,177619433541,None,0.03157,"Apr 05, 2021",0.0002189,"Mar 13, 2020"
27,BORA,1.12,/currencies/bora/,964244909.61,861250000,1205750000,None,1.66,"Nov 25, 2021",0.00621,"Jan 18, 2020"
28,Secret,6.68,/currencies/secret/,1003287554.55,149815729,190165060,None,10.64,"Oct 28, 2021",0.2554,"Nov 03, 2020"
31,Mina,2.73,/currencies/mina/,1020602898.66,374091004,824104972,None,9.91,"Jun 01, 2021",0.9233,"Jul 21, 2021"
33,Theta Fuel,0.22,/currencies/theta-fuel/,1147668822.79,5301214400,5301214400,None,0.6807,"Jun 09, 2021",0.0008897,"Mar 13, 2020"
34,Waves,10.72,/currencies/waves/,1149667695.24,107459716,107459716,None,41.33,"May 04, 2021",0.1227,"Aug 02, 2016"
45,BitTorrent (New),0.000002247,/currencies/bittorrent-new/,2095247914.22,932497500000000,990000000000000,None,0.000003054,"Jan 18, 2022",0.0000019,"Jan 22, 2022"
46,The Graph,0.45,/currencies/the-graph/,2139519539.30,4715735200,10000000000,10057044431,2.88,"Feb 12, 2021",None,"Dec 17, 2020"
47,PancakeSwap,8.03,/currencies/pancakeswap/,2141579130.86,266794005,266794005,None,44.18,"Apr 30, 2021",0.0002318,"Sep 29, 2020"
48,Gala,0.33,/currencies/gala/,2312010034.21,6977205436,35240112493,None,0.8367,"Nov 26, 2021",0.000151,"Dec 28, 2020"
49,Aave,175.75,/currencies/aave/,2373497128.97,13513437,16000000,16000000,666.86,"May 18, 2021",None,"Oct 02, 2020"
50,Harmony,0.21,/currencies/harmony/,2438787526.29,11701831218,13346405218,None,0.3798,"Oct 26, 2021",0.001257,"Mar 13, 2020"
51,Flow,7.83,/currencies/flow/,2488013160.84,318082398,1378211739,None,46.16,"Apr 05, 2021",4.34,"Jan 24, 2022"
52,EOS,2.55,/currencies/eos/,2501984501.50,980176807,1046763032,None,22.89,"Apr 29, 2018",0.4802,"Oct 23, 2017"
54,Klaytn,1.17,/currencies/klaytn/,3089792130.08,2631643888,10782297981,None,4.38,"Apr 02, 2021",0.05733,"May 06, 2020"
56,Monero,177.66,/currencies/monero/,3206456096.02,18076918,18076918,None,517.62,"May 07, 2021",0.213,"Jan 14, 2015"
57,Tezos,4.11,/currencies/tezos/,3604189983.15,877521626,905736491,None,9.18,"Oct 04, 2021",0.3146,"Dec 07, 2018"
59,Filecoin,23.11,/currencies/filecoin/,3678877986.47,159498411,159498411,None,237.24,"Apr 01, 2021",1.83,"Aug 29, 2019"
63,Internet Computer,21.44,/currencies/internet-computer/,4371015504.41,204047144,476876335,None,750.73,"May 10, 2021",None,"May 10, 2021"
66,Bitcoin BEP2,43303.54,/currencies/bitcoin-bep2/,4547877221.20,105149,112501,None,85563.99,"Oct 21, 2019",0.07685,"Jun 23, 2021"
70,Decentraland,3.20,/currencies/decentraland/,5865333832.35,1832139198,2193847327,None,5.90,"Nov 25, 2021",0.007883,"Oct 13, 2017"
72,UNUS SED LEO,6.46,/currencies/unus-sed-leo/,6169481804.56,953954130,985239504,None,8.04,"Feb 08, 2022",0.8036,"Dec 25, 2019"
75,TRON,0.07,/currencies/tron/,6942118750.89,101789822496,101789819139,None,0.3004,"Jan 05, 2018",0.001091,"Sep 15, 2017"
79,Cosmos,28.54,/currencies/cosmos/,8162103944.73,286370297,None,None,44.70,"Sep 20, 2021",1.13,"Mar 13, 2020"
81,Dai,1.00,/currencies/multi-collateral-dai/,10227467320.67,10234783913,10234783913,None,3.67,"Nov 16, 2021",0.9455,"May 10, 2020"
82,TerraUSD,1.00,/currencies/terrausd/,11272689055.69,11258807485,11258807295,None,1.05,"Jan 30, 2021",0.7929,"Dec 30, 2020"
83,Wrapped Bitcoin,43204.81,/currencies/wrapped-bitcoin/,11317856004.53,261914,261914,None,162188.26,"Nov 16, 2021",3330.12,"Feb 06, 2019"
86,Shiba Inu,0.00003028,/currencies/shiba-inu/,16624251516.25,549063278876302,589735030408323,None,0.00008845,"Oct 28, 2021",0.000000000082,"Sep 01, 2020"
87,Binance USD,1.00,/currencies/binance-usd/,17584562735.96,17575094794,17575094794,None,1.11,"Mar 12, 2020",0.8861,"Mar 13, 2020"
88,Dogecoin,0.15,/currencies/dogecoin/,20048312315.35,132670764300,132670764300,None,0.7376,"May 08, 2021",0.00008547,"May 07, 2015"
89,Polkadot,20.47,/currencies/polkadot-new/,20222009718.10,987579315,1103303471,None,55.00,"Nov 04, 2021",2.69,"Aug 20, 2020"
90,Terra,52.19,/currencies/terra-luna/,20974749289.42,401362694,818481818,None,103.33,"Dec 27, 2021",0.1201,"Mar 13, 2020"
91,Avalanche,90.58,/currencies/avalanche/,22239641131.93,245279107,395891290,None,146.22,"Nov 21, 2021",2.79,"Dec 31, 2020"
92,Solana,105.25,/currencies/solana/,33440468749.54,317630655,511616946,None,260.06,"Nov 06, 2021",0.5052,"May 11, 2020"
95,USD Coin,1.00,/currencies/usd-coin/,52103234992.62,52098051833,52098051833,None,2.35,"Nov 16, 2021",0.9292,"Mar 13, 2020"
97,Tether,1.00,/currencies/tether/,78430975067.45,78385451173,81074697053,None,1.22,"Feb 25, 2015",0.5683,"Mar 02, 2015"
98,Ethereum,3065.57,/currencies/ethereum/,366424227588.54,119529134,119529134,None,4891.70,"Nov 16, 2021",0.4209,"Oct 21, 2015"

In [58]:
# Checking which columns have None/NaN values
rawdf.isna().sum()

Name                    0
Price                   0
Link                    0
Market Cap              0
Circulating Supply      0
Total Supply            1
Max Supply             42
All Time High Value     1
All Time High Date      0
All Time Low Value      4
All Time Low Date       0
dtype: int64

In [59]:
rawdf.dtypes

Name                   object
Price                  object
Link                   object
Market Cap             object
Circulating Supply     object
Total Supply           object
Max Supply             object
All Time High Value    object
All Time High Date     object
All Time Low Value     object
All Time Low Date      object
dtype: object

## Converting Date Columns into DateTime

In [60]:
rawdf[['All Time High Date','All Time Low Date']] = rawdf[['All Time High Date','All Time Low Date']].apply(pd.to_datetime)

## Converting Columns into Numerical Datatypes

In [61]:
# Total and Max Supply kept as float to handle NaNs
conv_dict = {'Price': float,
             'Market Cap': float,
             'Circulating Supply': 'int64',
             'Total Supply': float,
             'Max Supply': float,
             'All Time High Value': float,
             'All Time Low Value':float}

In [62]:
rawdf = rawdf.astype(conv_dict)

In [63]:
rawdf.dtypes

Name                           object
Price                         float64
Link                           object
Market Cap                    float64
Circulating Supply              int64
Total Supply                  float64
Max Supply                    float64
All Time High Value           float64
All Time High Date     datetime64[ns]
All Time Low Value            float64
All Time Low Date      datetime64[ns]
dtype: object

## Converting remaining Volume columns into Int values
   ### Max Supply left as float to match required datatypes by instructor

In [64]:
rawdf['Total Supply'] = rawdf['Total Supply'].astype('Int64')
rawdf['Max Supply'] = rawdf['Max Supply'].apply(lambda x: None if math.isnan(x) else int(x))

## Picking up required columns for writing the csv with the cleaned dataframe

In [65]:
cleandf = rawdf[['Name', 'Price', 'Market Cap', 'Circulating Supply','Total Supply', 'Max Supply', 'All Time High Value',
       'All Time High Date', 'All Time Low Value', 'All Time Low Date']].copy()
cleandf.rename(columns={"All Time High Value":"All Time High Price","All Time Low Value":"All Time Low Price"},inplace=True)
cleandf.head()

,Name,Price,Market Cap,Circulating Supply,Total Supply,Max Supply,All Time High Price,All Time High Date,All Time Low Price,All Time Low Date
0,OKB,21.89,1.309902e+09,60000000,300000000,NaN,NaN,2000-01-01,NaN,2000-01-01
1,Basic Attention Token,0.88,1.315320e+09,1495079069,1500000000,1.500000e+09,1.9200,2021-11-28,0.066210,2017-07-16
2,Chiliz,0.22,1.324652e+09,5975068035,8888888888,8.888889e+09,0.8915,2021-03-13,0.004001,2019-09-27
3,Loopring,1.01,1.340276e+09,1329247433,1373873440,1.374514e+09,3.8300,2021-11-10,0.019860,2019-12-18
4,Curve DAO Token,3.17,1.404855e+09,443206806,1687553339,3.303030e+09,60.5000,2020-08-14,0.331600,2020-10-25

## Final Datatypes of Cleaned Dataframe

In [66]:
cleandf.dtypes

Name                           object
Price                         float64
Market Cap                    float64
Circulating Supply              int64
Total Supply                    Int64
Max Supply                    float64
All Time High Price           float64
All Time High Date     datetime64[ns]
All Time Low Price            float64
All Time Low Date      datetime64[ns]
dtype: object

## Writing Cleaned Dataframe to CSV

In [45]:
cleandf.to_csv("3-clean.csv",index=False)